### ISSUE TITLE
Comparison with react-navigation?

### ISSUE THREAD

**Issue by ghost** [tuckerconnelly/react-stack-nav#1]
I Just came across the library and was wondering the differences it has from react-navigation and which one would be better to choose. Since react-navigation is going to be merged in upstream react-native.

**Comment by tuckerconnelly** [comment]
`react-navigation` is certainly the blessed nav lib :) In my personal, biased opinion, react-navigation is too concrete and tries to do too much.

You can customize transitions with `react-stack-nav`, customize components, customize pretty much everything because it's abstract :)

`react-navigation` is focused on providing a native mobile navigator, with web support tacked on. `react-stack-nav` is focused on providing a general navigation library, inspired by the web's api, that can be used universally for every platform, with any UI components you want.

**Comment by tuckerconnelly** [comment]
react-stack-nav is able to do the same thing react-navigation does with 1/10 the code :P

**Comment by ghost** [comment]
But what about Performance implications?

**Comment by tuckerconnelly** [comment]
If you want to use native views for performance you totally can :) (believe `react-navigation` uses native views under the hood for speed)

Looking at this guy for example: https://github.com/react-native-community/react-native-tab-view

In that renderScene prop you could do a switch statement on the routeFragment :D
